---
title: "Course Project: Shiny Application and Reproducible Pitch"
author: "Diego Fernando Sanchez Ramos"
date: "9/7/2020"
output: ioslides_presentation
---

## Introduction
This presentation is part of the Course Project for the Coursera Developing Data Products class. 

The peer assessed assignment has two parts. 

-First, we need to create a Shiny application and deploy it on Rstudio's servers. 

-Second, we should use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about the application. 


This presentation adresses the second part of the course project. 

## Sources

-The app developed for the first part of the assignment is avalilable at:

https://dfsanchez.shinyapps.io/MarketAppDiegoSanchez/

-Source code for ui.R and server.R files are available on the GitHub:

https://github.com/dfsanchez2020/Developing_Data_Pro.git


## Applicability

Stock market comparison

-This application helps you compare the annual stock market history of the world's leading companies.

-The only variable considered for this app is the stock market stability indicator throughout the period 01/01/2020 - 08/07/2020.

-The 7 most representative companies in the market are chosen to develop the app, taking into account its share indicator.

## Companies taken into account

-Apple
-Cisco
-IBM
-Facebook
-Twitter
-Microsoft
-Google

Note: the information source is extracted directly from Yahoo through the "quantmod" library

## Thank you

Please See the app in https://dfsanchez.shinyapps.io/MarketAppDiegoSanchez/
